### ISSUE TITLE
Tracking issue of Twig test coverage

### ISSUE THREAD

**Issue by Nercury** [Nercury/twig-rs#1]
The aim is to write all the [Twig test suite](https://github.com/twigphp/Twig/tree/1.x/test/Twig/Tests) in Rust.
- [x] Lexer Tests
- [x] Test fixture runner, so we can run [these](https://github.com/twigphp/Twig/blob/1.x/test/Twig/Tests/Fixtures/filters/batch_with_keys.test) (issue #2)
- [ ] Core extension and sandbox tests.
- [ ] Core node tests.
- [ ] Expression tests.
- [ ] Parser tests.
- [ ] Loader/Environment tests.
